eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka
  instance:
    preferIpAddress: true

datasource:
  url: jdbc:postgresql://192.168.99.100:5432/LifeBio
  username: crazymonkey
  password: J@ck_@55

jpa:
  show-sql: true
  hibernate:
      ddl-auto: create-drop