server:
  port: 4002

spring:
  application:
    name: lifebiocontactdetails
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true