server:
  port: 8888

spring:
  application:
    name: lifebioconfig
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true