server:
  port: 4001

spring:
  application:
    name: lifebiofeign
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true