server:
  port: 4001

spring:
  application:
    name: lifebioapigateway
    version: 1.0.0

zuul:
  routes:
    lifeBioUI:
      serviceId: LifeBioAPIGateway
  host:
    socket-timeout-millis: 30000
  sensitiveHeaders: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 29000

security:
  basic:
    enabled: false

feign:
  oauth2:
    enabled: true
  hystrix:
    enabled: false
