server:
  port: 4003

spring:
  application:
    name: lifebioperson
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka
  instance:
    preferIpAddress: true